server:
  port: 8082
       
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gokul?useSSL=false
    username: gokul
    password: gokul
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
  application:
    name: AUTHOR-SERVICE